/**
 * Cloud Generate – Proof surface helpers.
 *
 * Deterministic fixtures and a recording executor for contract-level proofs.
 * The executor is an *honest stub*: it records what was passed in and returns
 * a canned response so tests can verify the endpoint's observable behavior
 * without reaching a real Cloud runtime.
 */

import type { CloudGenerateRequest } from '../request-types.js';
import type { CloudGenerateResponse } from '../response-types.js';
import type { CloudExecutor } from '../generate-endpoint.js';

/* ------------------------------------------------------------------ */
/*  Deterministic ID factory                                          */
/* ------------------------------------------------------------------ */

export function createStableIdFactory(prefix = 'proof'): () => string {
  let seq = 0;
  return () => `${prefix}-${++seq}`;
}

/* ------------------------------------------------------------------ */
/*  Canonical fixtures                                                */
/* ------------------------------------------------------------------ */

const FIXED_TIMESTAMP = '2026-01-01T00:00:00.000Z';

export function validProofRequest(
  overrides: Partial<CloudGenerateRequest> = {},
): CloudGenerateRequest {
  return {
    auth: { token: 'tok_proof' },
    workspace: { workspaceId: 'ws_proof', environment: 'test' },
    body: { spec: { kind: 'string', raw: 'proof-input' } },
    ...overrides,
  };
}

export function successProofResponse(requestId: string): CloudGenerateResponse {
  return {
    ok: true,
    artifacts: [
      { id: 'art-1', name: 'proof-output.ts', content: 'export const ok = true;', mimeType: 'text/typescript' },
    ],
    warnings: [
      { code: 'PROOF', message: 'Response generated by proof executor – not a real Cloud runtime' },
    ],
    assumptions: [
      { key: 'runtime', value: 'stub', reason: 'No Cloud runtime wired; proof executor used' },
    ],
    followUpActions: [
      { label: 'Verify', action: 'verify-output', payload: { target: 'proof' } },
    ],
    validation: { valid: true, issues: [] },
    receipt: {
      requestId,
      startedAt: FIXED_TIMESTAMP,
      completedAt: FIXED_TIMESTAMP,
      durationMs: 0,
    },
  };
}

/* ------------------------------------------------------------------ */
/*  Recording executor – honest stub                                  */
/* ------------------------------------------------------------------ */

export interface RecordingExecutorState {
  calls: CloudGenerateRequest[];
  response: CloudGenerateResponse;
}

/**
 * Creates an executor that records every request it receives and returns
 * a deterministic canned response. This is a *stubbed runtime seam*: no
 * actual generation happens.
 */
export function createRecordingExecutor(
  requestId: string,
): { executor: CloudExecutor; state: RecordingExecutorState } {
  const state: RecordingExecutorState = {
    calls: [],
    response: successProofResponse(requestId),
  };

  const executor: CloudExecutor = {
    async execute(request: CloudGenerateRequest): Promise<CloudGenerateResponse> {
      state.calls.push(request);
      return state.response;
    },
  };

  return { executor, state };
}
